FROM golang:1.15 as builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

COPY cmd/ cmd/
COPY api/ api/
COPY pkg/ pkg/
COPY controllers/ controllers/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o node ./cmd/node/

FROM alpine
WORKDIR /
COPY --from=builder /workspace/node .

ENTRYPOINT ["/node"]
