
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: node-role
rules:
- apiGroups:
  - vpc.scaleway.com
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - vpc.scaleway.com
  resources:
  - networkinterfaces/status
  verbs:
  - get
  - patch
- apiGroups:
  - vpc.scaleway.com
  resources:
  - privatenetworks
  verbs:
  - get
  - list
  - watch
