---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "scaleway-k8s-vpc.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "scaleway-k8s-vpc.controller.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scaleway-k8s-vpc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "scaleway-k8s-vpc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        args:
        - --enable-leader-election
        command:
        - /controller
        env:
        - name: CONFIGMAP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: {{ tpl .Values.controller.secret.name . }}
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        resources: {{ toYaml .Values.controller.resources | nindent 12 }}
    {{- if .Values.controller.nodeSelector }}
      nodeSelector: {{ toYaml .Values.controller.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.tolerations }}
      tolerations: {{ toYaml .Values.controller.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.affinity }}
      affinity: {{ toYaml .Values.controller.affinity | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "scaleway-k8s-vpc.controller.fullname" . }}
      terminationGracePeriodSeconds: 10